<a href="https://colab.research.google.com/github/bharatikasture573-cyber/Car_Datasets/blob/main/Car_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as

In [3]:
from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print(fn)

Saving car_dataset.csv to car_dataset.csv
car_dataset.csv

In [7]:
filepath = '/content/car_dataset.csv'
df = pd.read_csv(filepath)
print(df)

     car_id    brand      model variant fuel_type  engine_cc  mileage_kmpl  \
0         1   Toyota  Model_899      V4    Petrol       2490         19.17
1         2     Tata  Model_701      V2  Electric       1205         12.45
2         3  Hyundai  Model_776      V2  Electric       2321         17.70
3         4     Tata  Model_774      V1    Petrol       2441         24.38
4         5      Kia  Model_856      V1    Petrol       1570         20.64
..      ...      ...        ...     ...       ...        ...           ...
995     996   Toyota  Model_159      V2  Electric       2626         20.29
996     997   Maruti  Model_271      V2  Electric       2168         21.76
997     998    Honda  Model_453      V4    Petrol       2498         10.36
998     999     Tata  Model_856      V5    Diesel       1194         11.00
999    1000  Hyundai  Model_722      V5  Electric       1060         14.14

       price   color  year  ... accessories_cost extended_warranty  \
0    1852981    Blue  2024  ...             9534               Yes
1    1847906   Black  2025  ...            45814               Yes
2    1792525    Grey  2023  ...            36389               Yes
3    1542444  Silver  2022  ...            28253                No
4    1369388   White  2022  ...            14465               Yes
..       ...     ...   ...  ...              ...               ...
995   736903  Silver  2022  ...            34470                No
996   981305   White  2025  ...            24439               Yes
997   835083   Black  2022  ...            29519                No
998  1131582    Blue  2016  ...            31124                No
999  1956701   White  2023  ...            21927               Yes

    roadside_assistance insurance_type  user_reviews  user_rating  \
0                    No  Comprehensive           393         4.62
1                    No  Comprehensive            27         3.34
2                    No    Third Party           695         4.51
3                    No    Third Party            76         4.51
4                   Yes  Comprehensive           347         4.74
..                  ...            ...           ...          ...
995                 Yes  Comprehensive           311         3.34
996                 Yes    Third Party            26         4.32
997                  No  Comprehensive           512         3.75
998                 Yes  Comprehensive           762         3.63
999                 Yes  Comprehensive           446         3.75

     popularity_index  stock_status  launch_year  discontinued
0                  43  Out of Stock         2019           Yes
1                  72      In Stock         2018           Yes
2                  92  Out of Stock         2017            No
3                  10  Out of Stock         2020            No
4                  20      In Stock         2016            No
..                ...           ...          ...           ...
995                55  Out of Stock         2015           Yes
996                50  Out of Stock         2015           Yes
997                 9      In Stock         2016           Yes
998                75      In Stock         2020           Yes
999                90      In Stock         2015           Yes

[1000 rows x 79 columns]

In [8]:
df.head()

,car_id,brand,model,variant,fuel_type,engine_cc,mileage_kmpl,price,color,year,...,accessories_cost,extended_warranty,roadside_assistance,insurance_type,user_reviews,user_rating,popularity_index,stock_status,launch_year,discontinued
0,1,Toyota,Model_899,V4,Petrol,2490,19.17,1852981,Blue,2024,...,9534,Yes,No,Comprehensive,393,4.62,43,Out of Stock,2019,Yes
1,2,Tata,Model_701,V2,Electric,1205,12.45,1847906,Black,2025,...,45814,Yes,No,Comprehensive,27,3.34,72,In Stock,2018,Yes
2,3,Hyundai,Model_776,V2,Electric,2321,17.70,1792525,Grey,2023,...,36389,Yes,No,Third Party,695,4.51,92,Out of Stock,2017,No
3,4,Tata,Model_774,V1,Petrol,2441,24.38,1542444,Silver,2022,...,28253,No,No,Third Party,76,4.51,10,Out of Stock,2020,No
4,5,Kia,Model_856,V1,Petrol,1570,20.64,1369388,White,2022,...,14465,Yes,Yes,Comprehensive,347,4.74,20,In Stock,2016,No

In [9]:
df.tail()

,car_id,brand,model,variant,fuel_type,engine_cc,mileage_kmpl,price,color,year,...,accessories_cost,extended_warranty,roadside_assistance,insurance_type,user_reviews,user_rating,popularity_index,stock_status,launch_year,discontinued
995,996,Toyota,Model_159,V2,Electric,2626,20.29,736903,Silver,2022,...,34470,No,Yes,Comprehensive,311,3.34,55,Out of Stock,2015,Yes
996,997,Maruti,Model_271,V2,Electric,2168,21.76,981305,White,2025,...,24439,Yes,Yes,Third Party,26,4.32,50,Out of Stock,2015,Yes
997,998,Honda,Model_453,V4,Petrol,2498,10.36,835083,Black,2022,...,29519,No,No,Comprehensive,512,3.75,9,In Stock,2016,Yes
998,999,Tata,Model_856,V5,Diesel,1194,11.00,1131582,Blue,2016,...,31124,No,Yes,Comprehensive,762,3.63,75,In Stock,2020,Yes
999,1000,Hyundai,Model_722,V5,Electric,1060,14.14,1956701,White,2023,...,21927,Yes,Yes,Comprehensive,446,3.75,90,In Stock,2015,Yes

In [10]:
df.shape

(1000, 79)

In [11]:
df.columns

Index(['car_id', 'brand', 'model', 'variant', 'fuel_type', 'engine_cc',
       'mileage_kmpl', 'price', 'color', 'year', 'transmission', 'owner_type',
       'registration_state', 'insurance_status', 'seating_capacity',
       'max_power_bhp', 'torque_nm', 'fuel_tank_capacity', 'top_speed',
       'weight_kg', 'boot_space', 'ground_clearance', 'wheelbase', 'airbags',
       'abs', 'traction_control', 'cruise_control', 'sunroof',
       'infotainment_system', 'navigation', 'bluetooth', 'usb_ports',
       'climate_control', 'rear_ac', 'parking_sensors', 'parking_camera',
       'headlight_type', 'tail_light_type', 'wheel_type', 'tyre_type',
       'battery_type', 'range_km', 'charging_time', 'service_cost',
       'warranty_years', 'rating', 'launch_country', 'emission_norm',
       'odometer', 'insurance_cost', 'registration_cost', 'road_tax',
       'resale_value', 'availability', 'delivery_time', 'discount_offer',
       'dealer_name', 'dealer_city', 'dealer_rating', 'test_drive',
       'finance_available', 'emi_option', 'down_payment', 'interest_rate',
       'loan_tenure', 'number_of_services', 'first_service_km',
       'second_service_km', 'third_service_km', 'accessories_cost',
       'extended_warranty', 'roadside_assistance', 'insurance_type',
       'user_reviews', 'user_rating', 'popularity_index', 'stock_status',
       'launch_year', 'discontinued'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 79 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_id               1000 non-null   int64
 1   brand                1000 non-null   object
 2   model                1000 non-null   object
 3   variant              1000 non-null   object
 4   fuel_type            1000 non-null   object
 5   engine_cc            1000 non-null   int64
 6   mileage_kmpl         1000 non-null   float64
 7   price                1000 non-null   int64
 8   color                1000 non-null   object
 9   year                 1000 non-null   int64
 10  transmission         1000 non-null   object
 11  owner_type           1000 non-null   object
 12  registration_state   1000 non-null   object
 13  insurance_status     1000 non-null   object
 14  seating_capacity     1000 non-null   int64
 15  max_power_bhp        1000 non-null   float64
 16  torque_nm            1000 non-null   float64
 17  fuel_tank_capacity   1000 non-null   int64
 18  top_speed            1000 non-null   int64
 19  weight_kg            1000 non-null   int64
 20  boot_space           1000 non-null   int64
 21  ground_clearance     1000 non-null   int64
 22  wheelbase            1000 non-null   int64
 23  airbags              1000 non-null   int64
 24  abs                  1000 non-null   object
 25  traction_control     1000 non-null   object
 26  cruise_control       1000 non-null   object
 27  sunroof              1000 non-null   object
 28  infotainment_system  1000 non-null   object
 29  navigation           1000 non-null   object
 30  bluetooth            1000 non-null   object
 31  usb_ports            1000 non-null   int64
 32  climate_control      1000 non-null   object
 33  rear_ac              1000 non-null   object
 34  parking_sensors      1000 non-null   object
 35  parking_camera       1000 non-null   object
 36  headlight_type       1000 non-null   object
 37  tail_light_type      1000 non-null   object
 38  wheel_type           1000 non-null   object
 39  tyre_type            1000 non-null   object
 40  battery_type         1000 non-null   object
 41  range_km             1000 non-null   int64
 42  charging_time        1000 non-null   int64
 43  service_cost         1000 non-null   int64
 44  warranty_years       1000 non-null   int64
 45  rating               1000 non-null   float64
 46  launch_country       1000 non-null   object
 47  emission_norm        1000 non-null   object
 48  odometer             1000 non-null   int64
 49  insurance_cost       1000 non-null   int64
 50  registration_cost    1000 non-null   int64
 51  road_tax             1000 non-null   int64
 52  resale_value         1000 non-null   int64
 53  availability         1000 non-null   object
 54  delivery_time        1000 non-null   int64
 55  discount_offer       1000 non-null   int64
 56  dealer_name          1000 non-null   object
 57  dealer_city          1000 non-null   object
 58  dealer_rating        1000 non-null   float64
 59  test_drive           1000 non-null   object
 60  finance_available    1000 non-null   object
 61  emi_option           1000 non-null   object
 62  down_payment         1000 non-null   int64
 63  interest_rate        1000 non-null   float64
 64  loan_tenure          1000 non-null   int64
 65  number_of_services   1000 non-null   int64
 66  first_service_km     1000 non-null   int64
 67  second_service_km    1000 non-null   int64
 68  third_service_km     1000 non-null   int64
 69  accessories_cost     1000 non-null   int64
 70  extended_warranty    1000 non-null   object
 71  roadside_assistance  1000 non-null   object
 72  insurance_type       1000 non-null   object
 73  user_reviews         1000 non-null   int64
 74  user_rating          1000 non-null   float64
 75  popularity_index     1000 non-null   int64
 76  stock_status         1000 non-null   object
 77  launch_year          1000 non-null   int64
 78  discontinued         1000 non-null   object
dtypes: float64(7), int64(34), object(38)
memory usage: 617.3+ KB

In [13]:
df.describe()

,car_id,engine_cc,mileage_kmpl,price,year,seating_capacity,max_power_bhp,torque_nm,fuel_tank_capacity,top_speed,...,loan_tenure,number_of_services,first_service_km,second_service_km,third_service_km,accessories_cost,user_reviews,user_rating,popularity_index,launch_year
count,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000
mean,500.500000,1933.263000,17.528070,1.236199e+06,2019.951000,5.515000,123.210500,250.500420,44.932000,168.741000,...,35.841000,6.433000,7455.643000,14825.429000,25027.355000,27342.012000,509.397000,3.99766,49.667000,2019.841000
std,288.819436,629.930957,4.379798,4.419122e+05,3.166801,1.097716,42.917089,86.727341,8.904418,29.964743,...,14.494682,2.258453,1453.820766,2890.387611,2893.623814,13136.027501,290.002526,0.55873,28.622323,3.183057
min,1.000000,800.000000,10.040000,5.021910e+05,2015.000000,4.000000,50.290000,100.280000,30.000000,120.000000,...,12.000000,3.000000,5000.000000,10008.000000,20026.000000,5042.000000,0.000000,3.00000,1.000000,2015.000000
25%,250.750000,1407.750000,13.765000,8.602878e+05,2017.000000,5.000000,86.372500,177.507500,37.000000,141.000000,...,23.000000,4.000000,6209.000000,12310.000000,22434.750000,15808.750000,259.500000,3.50000,26.000000,2017.000000
50%,500.500000,1922.000000,17.495000,1.226285e+06,2020.000000,6.000000,122.895000,248.415000,45.000000,169.000000,...,35.000000,6.000000,7425.500000,14765.000000,25069.500000,26951.500000,517.000000,3.97000,48.000000,2020.000000
75%,750.250000,2497.250000,21.340000,1.627011e+06,2023.000000,6.000000,159.402500,325.837500,53.000000,195.000000,...,49.000000,8.000000,8677.250000,17325.250000,27615.500000,39285.000000,761.250000,4.47250,74.000000,2023.000000
max,1000.000000,3000.000000,24.990000,1.999928e+06,2025.000000,7.000000,199.970000,399.690000,60.000000,220.000000,...,60.000000,10.000000,9999.000000,20000.000000,29994.000000,49894.000000,999.000000,5.00000,100.000000,2025.000000

In [14]:
df.dtypes

car_id                int64
brand                object
model                object
variant              object
fuel_type            object
                     ...
user_rating         float64
popularity_index      int64
stock_status         object
launch_year           int64
discontinued         object
Length: 79, dtype: object

In [15]:
df.isnull() .sum()

car_id              0
brand               0
model               0
variant             0
fuel_type           0
                   ..
user_rating         0
popularity_index    0
stock_status        0
launch_year         0
discontinued        0
Length: 79, dtype: int64

In [16]:
df.nunique()

car_id              1000
brand                  7
model                597
variant                5
fuel_type              3
                    ...
user_rating          198
popularity_index     100
stock_status           2
launch_year           11
discontinued           2
Length: 79, dtype: int64

In [17]:
df.sample(5)

,car_id,brand,model,variant,fuel_type,engine_cc,mileage_kmpl,price,color,year,...,accessories_cost,extended_warranty,roadside_assistance,insurance_type,user_reviews,user_rating,popularity_index,stock_status,launch_year,discontinued
434,435,Mahindra,Model_943,V2,Petrol,2400,17.26,772989,Grey,2021,...,46843,No,Yes,Comprehensive,536,4.85,91,In Stock,2018,Yes
461,462,Tata,Model_770,V5,Electric,2338,22.62,1579731,Grey,2019,...,39843,No,No,Comprehensive,186,3.57,68,In Stock,2020,Yes
654,655,Hyundai,Model_322,V3,Petrol,1867,17.94,1850641,White,2023,...,28245,No,No,Comprehensive,504,4.16,79,In Stock,2024,No
508,509,Honda,Model_784,V3,Diesel,1396,24.51,1413094,Red,2024,...,45843,No,Yes,Third Party,24,4.67,38,In Stock,2023,No
311,312,Honda,Model_844,V2,Electric,2636,12.76,1548098,Black,2019,...,11362,Yes,Yes,Third Party,276,3.01,10,Out of Stock,2021,Yes

In [18]:
df.value_counts()

car_id  brand     model      variant  fuel_type  engine_cc  mileage_kmpl  price    color   year  transmission  owner_type  registration_state  insurance_status  seating_capacity  max_power_bhp  torque_nm  fuel_tank_capacity  top_speed  weight_kg  boot_space  ground_clearance  wheelbase  airbags  abs  traction_control  cruise_control  sunroof  infotainment_system  navigation  bluetooth  usb_ports  climate_control  rear_ac  parking_sensors  parking_camera  headlight_type  tail_light_type  wheel_type  tyre_type  battery_type  range_km  charging_time  service_cost  warranty_years  rating  launch_country  emission_norm  odometer  insurance_cost  registration_cost  road_tax  resale_value  availability  delivery_time  discount_offer  dealer_name  dealer_city  dealer_rating  test_drive  finance_available  emi_option  down_payment  interest_rate  loan_tenure  number_of_services  first_service_km  second_service_km  third_service_km  accessories_cost  extended_warranty  roadside_assistance  insurance_type  user_reviews  user_rating  popularity_index  stock_status  launch_year  discontinued
1000    Hyundai   Model_722  V5       Electric   1060       14.14         1956701  White   2023  Manual        First       TS                  Expired           6                 130.20         387.77     42                  197        1675       545         206               2133       6        No   No                Yes             No       Touchscreen          No          Yes        2          Auto             Yes      Yes              No              Halogen         LED              Alloy       Tubeless   Lead Acid     325       6              9042          2               3.32    India           BS6            98877     42037           38663              63848     439835        Available     22             14734           Dealer_2     Delhi        3.34           Yes         No                 No          158963        10.11          24           7                   8421              15354              25523             21927             Yes                Yes                  Comprehensive   446           3.75         90                In Stock      2015         Yes             1
1       Toyota    Model_899  V4       Petrol     2490       19.17         1852981  Blue    2024  Automatic     Second      DL                  Active            6                 158.53         352.05     59                  187        1565       223         189               2124       7        No   Yes               Yes             Yes      Touchscreen          No          No         2          Auto             No       Yes              No              Halogen         Bulb             Steel       Tube       Lead Acid     464       5              16905         1               3.50    India           BS6            87562     30023           27202              64898     479662        Available     2              15830           Dealer_20    Bangalore    4.52           No          No                 No          145948        10.14          45           5                   8460              14744              22161             9534              Yes                No                   Comprehensive   393           4.62         43                Out of Stock  2019         Yes             1
2       Tata      Model_701  V2       Electric   1205       12.45         1847906  Black   2025  Manual        Second      MH                  Active            5                 84.72          356.89     51                  189        1447       561         205               2168       6        No   No                No              No       Touchscreen          No          No         3          Auto             Yes      Yes              No              LED             Bulb             Alloy       Tube       Lead Acid     332       5              17306         4               3.40    India           BS6            93192     32037           31511              61919     726822        Available     4              12536           Dealer_19    Pune         3.65           No          Yes                Yes         186285        11.23          29           9                   5765              17712              29978             45814             Yes                No                   Comprehensive   27            3.34         72                In Stock      2018         Yes             1
3       Hyundai   Model_776  V2       Electric   2321       17.70         1792525  Grey    2023  Manual        First       TS                  Expired           4                 167.94         333.63     53                  196        1429       584         181               2705       7        No   No                Yes             Yes      Touchscreen          No          Yes        4          Manual           Yes      No               No              Halogen         Bulb             Steel       Tubeless   Lead Acid     482       7              14784         2               4.84    India           BS6            1975      25611           38237              92520     292346        Available     16             22643           Dealer_7     Bangalore    3.01           No          Yes                Yes         177414        7.94           16           7                   6259              15346              20903             36389             Yes                No                   Third Party     695           4.51         92                Out of Stock  2017         No              1
4       Tata      Model_774  V1       Petrol     2441       24.38         1542444  Silver  2022  Automatic     First       KA                  Active            6                 127.48         169.48     47                  206        1926       421         169               2722       7        Yes  No                No              No       Touchscreen          No          No         2          Auto             No       Yes              Yes             Halogen         LED              Steel       Tube       Lead Acid     269       3              8002          3               3.85    India           BS6            67764     17857           50435              41178     554307        Available     2              37501           Dealer_3     Mumbai       3.49           Yes         No                 No          159210        9.11           45           5                   9234              13659              27486             28253             No                 No                   Third Party     76            4.51         10                Out of Stock  2020         No              1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ..
13      Hyundai   Model_776  V1       Petrol     2802       23.20         1752646  Silver  2025  Manual        First       KA                  Active            6                 106.66         325.45     55                  203        1718       295         153               2509       6        No   Yes               No              No       Touchscreen          No          Yes        4          Manual           Yes      No               Yes             Halogen         LED              Alloy       Tube       Lead Acid     326       7              13641         4               3.66    India           BS6            17069     26076           79173              78914     256442        Available     27             32706           Dealer_14    Bangalore    3.15           No          Yes                Yes         97975         9.12           46           5                   6532              11384              21762             11311             Yes                Yes                  Third Party     877           4.82         77                In Stock      2020         No              1
12      Maruti    Model_593  V5       Petrol     2338       13.99         782558   Red     2015  Manual        Second      TS                  Expired           4                 74.25          283.61     44                  131        1613       526         206               2567       2        Yes  No                Yes             Yes      Touchscreen          Yes         No         4          Auto             Yes      Yes              Yes             LED             LED              Alloy       Tube       Lithium       338       4              15661         5               4.27    India           BS6            16158     14915           29235              81644     445896        Available     7              287             Dealer_4     Pune         4.51           Yes         No                 No          162549        9.30           56           7                   5235              18130              23861             10436             Yes                No                   Third Party     611           3.84         69                Out of Stock  2022         No              1
11      Tata      Model_623  V1       Petrol     2915       12.49         689526   Grey    2025  Automatic     Second      TS                  Active            6                 93.05          359.24     43                  158        1321       251         212               2800       4        No   Yes               Yes             No       Touchscreen          No          No         1          Manual           No       Yes              No              LED             LED              Alloy       Tubeless   Lead Acid     229       6              17670         3               4.17    India           BS6            4013      35916           43229              42156     267182        Available     25             17020           Dealer_11    Mumbai       4.63           No          Yes                No          168174        10.48          39           5                   9713              19390              22861             15712             No                 Yes                  Comprehensive   643           4.46         48                Out of Stock  2019         Yes             1
10      Hyundai   Model_616  V3       Electric   2972       20.10         1948209  Black   2019  Automatic     Second      KA                  Expired           7                 181.07         179.00     38                  214        1374       252         153               2974       6        No   Yes               No              No       Touchscreen          No          Yes        3          Manual           No       Yes              Yes             LED             Bulb             Steel       Tubeless   Lead Acid     394       3              17050         1               3.60    India           BS6            38356     41087           65518              69980     634435        Available     20             16100           Dealer_3     Mumbai       3.71           No          No                 No          169231        7.38           38           8                   6605              11752              23476             38631             Yes                Yes                  Comprehensive   25            4.24         82                Out of Stock  2022         No              1
9       Mahindra  Model_110  V2       Electric   2006       11.14         1408059  Black   2016  Automatic     First       DL                  Expired           4                 158.55         124.32     40                  145        1086       461         191               2205       3        Yes  Yes               Yes             Yes      Touchscreen          No          Yes        2          Manual           Yes      Yes              No              Halogen         Bulb             Alloy       Tube       Lead Acid     310       10             18042         4               3.96    India           BS6            98351     32353           52047              85435     295016        Available     13             1731            Dealer_14    Mumbai       3.73           No          No                 No          154709        10.35          16           4                   5387              17511              29880             18181             Yes                Yes                  Comprehensive   724           4.79         60                Out of Stock  2017         No              1
Name: count, Length: 1000, dtype: int64